name: qld_alert_app

description: QLD Alert Portfolio App

publish_to: 'none'

version: 1.0.33+60

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.1

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.3.0
  in_app_purchase: ^3.2.3
  fl_chart: ^0.68.0
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.2.3
  web_socket_channel: ^3.0.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/QLD_DIP_ALERT_512.png
    - assets/qld_widget_icon.png
