part of '../main.dart';

class ChartListItem {
  const ChartListItem({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.symbolPath,
    required this.color,
    required this.icon,
  });

  final String id;
  final String title;
  final String subtitle;
  final String symbolPath;
  final Color color;
  final IconData icon;
}

class ExchangeListItem {
  const ExchangeListItem({
    required this.id,
    required this.symbolPath,
    required this.color,
    required this.icon,
  });

  final String id;
  final String symbolPath;
  final Color color;
  final IconData icon;
}

Widget buildTickerBadge(
  String label,
  Color color,
) {
  return Container(
    width: 32,
    height: 32,
    padding: const EdgeInsets.symmetric(horizontal: 3),
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(8),
      color: color.withValues(alpha: 0.12),
      border: Border.all(
        color: color.withValues(alpha: 0.35),
      ),
    ),
    alignment: Alignment.center,
    child: FittedBox(
      fit: BoxFit.scaleDown,
      child: Text(
        label,
        maxLines: 1,
        style: TextStyle(
          color: color,
          fontSize: 11,
          fontWeight: FontWeight.w700,
          letterSpacing: 0,
        ),
      ),
    ),
  );
}

ChartListItem popularStockChartItem(
  String ticker,
  String name,
  String exchange,
  Color color,
) {
  final id = 'stock${ticker.replaceAll(RegExp(r'[^A-Za-z0-9]'), '')}';

  return ChartListItem(
    id: id,
    title: '$ticker  $name',
    subtitle: '$exchange:$ticker',
    symbolPath: '$exchange-${ticker.replaceAll('.', '.')}',
    color: color,
    icon: Icons.trending_up_rounded,
  );
}

ChartListItem popularEtfChartItem(
  String ticker,
  String name,
  String exchange,
  Color color,
) {
  return ChartListItem(
    id: 'etf$ticker',
    title: '$ticker  $name',
    subtitle: '$exchange:$ticker',
    symbolPath: '$exchange-$ticker',
    color: color,
    icon: Icons.pie_chart_rounded,
  );
}

ChartListItem commodityChartItem(
  String id,
  String title,
  String subtitle,
  String symbolPath,
  Color color,
) {
  return ChartListItem(
    id: 'commodity$id',
    title: title,
    subtitle: subtitle,
    symbolPath: symbolPath,
    color: color,
    icon: Icons.grain_rounded,
  );
}

ChartListItem globalMegaCapChartItem(
  String id,
  String title,
  String subtitle,
  String symbolPath,
  Color color,
) {
  return ChartListItem(
    id: 'global$id',
    title: title,
    subtitle: subtitle,
    symbolPath: symbolPath,
    color: color,
    icon: Icons.public_rounded,
  );
}

ChartListItem countryLargeCapChartItem(
  String id,
  String title,
  String subtitle,
  String symbolPath,
  Color color,
) {
  return ChartListItem(
    id: 'country$id',
    title: title,
    subtitle: subtitle,
    symbolPath: symbolPath,
    color: color,
    icon: Icons.business_center_rounded,
  );
}

ChartListItem cryptoChartItem(
  String ticker,
  String name,
  Color color,
) {
  return ChartListItem(
    id: 'crypto$ticker',
    title: '$ticker  $name',
    subtitle: 'CRYPTO:$ticker',
    symbolPath: 'CRYPTO-${ticker}USD',
    color: color,
    icon: Icons.currency_bitcoin_rounded,
  );
}

ChartListItem macroChartItem(
  String id,
  String title,
  String subtitle,
  String symbolPath,
  Color color,
) {
  return ChartListItem(
    id: 'macro$id',
    title: title,
    subtitle: subtitle,
    symbolPath: symbolPath,
    color: color,
    icon: Icons.query_stats_rounded,
  );
}

const Map<String, String> _chartSearchAliases = {
  'AAPL': '애플 アップル 苹果 蘋果 Эпл',
  'MSFT': '마이크로소프트 マイクロソフト 微软 微軟 Майкрософт',
  'NVDA': '엔비디아 エヌビディア 英伟达 輝達 Нвидиа',
  'AMZN': '아마존 アマゾン 亚马逊 亞馬遜 Амазон',
  'GOOGL': '구글 알파벳 グーグル アルファベット 谷歌 字母表 Гугл Алфавит',
  'META': '메타 페이스북 メタ フェイスブック 元宇宙 脸书 臉書 Мета Фейсбук',
  'TSLA': '테슬라 テスラ 特斯拉 Тесла',
  'AVGO': '브로드컴 ブロードコム 博通 Бродком',
  'BRK.B': '버크셔 해서웨이 バークシャー 伯克希尔 波克夏 Беркшир',
  'LLY': '일라이 릴리 イーライリリー 礼来 禮來 Эли Лилли',
  'JPM': '제이피모건 JP모건 JPモルガン 摩根大通 Джей피 Морган',
  'V': '비자 ビザ 维萨 維薩 Виза',
  'UNH': '유나이티드헬스 ユナイテッドヘルス 联合健康 聯合健康 Юнайтедヘルス',
  'XOM': '엑슨모빌 エクソンモービル 埃克森美孚 Эксон',
  'MA': '마스터카드 マスターカード 万事达 萬事達 Мастеркард',
  'COST': '코스트코 コストコ 好市多 Костко',
  'HD': '홈디포 ホームデポ 家得宝 家得寶 Хоум Депо',
  'NFLX': '넷플릭스 ネットフリックス 奈飞 奈飛 Нетфликс',
  'PG': '피앤지 P&G プロクター 宝洁 寶潔 Проктер',
  'JNJ': '존슨앤존슨 ジョンソン 强生 強生 Джонсон',
  'WMT': '월마트 ウォルマート 沃尔玛 沃爾瑪 Волмарт',
  'ABBV': '애브비 アッヴィ 艾伯维 艾伯維 Эббви',
  'BAC': '뱅크오브아메리카 バンクオブアメリカ 美国银行 美國銀行 Банк Америка',
  'CRM': '세일즈포스 セールスフォース 赛富时 賽富時 Сейл즈форс',
  'ORCL': '오라클 オラクル 甲骨文 Оракл',
  'KO': '코카콜라 コカコーラ 可口可乐 可口可樂 Кока Кола',
  'CVX': '쉐브론 셰브론 シェブロン 雪佛龙 雪佛龍 Шеврон',
  'AMD': '에이엠디 AMD エーエムディ 超微 半导体 半導體',
  'MRK': '머크 メルク 默克 Мерк',
  'CSCO': '시스코 シスコ 思科 Циско',
  'WFC': '웰스파고 ウェルズファーゴ 富国银行 富國銀行 Уэллс Фарго',
  'MCD': '맥도날드 マクドナルド 麦当劳 麥當勞 Макдональдс',
  'PEP': '펩시 펩시코 ペプシ 百事 Пепси',
  'ADBE': '어도비 アドビ 奥多比 奧多比 Адобе',
  'IBM': '아이비엠 IBM アイビーエム 国际商业机器 國際商業機器',
  'QCOM': '퀄컴 クアルコム 高通 Куалком',
  'CAT': '캐터필러 キャタピラー 卡特彼勒 Катерпиллар',
  'DIS': '디즈니 ディズニー 迪士尼 Дисней',
  'UBER': '우버 ウーバー 优步 優步 Убер',
  'SBUX': '스타벅스 スターバックス 星巴克 Старбакс',
  'PLTR': '팔란티어 パランティア 帕兰提尔 帕蘭提爾 Палантир',
  'SHOP': '쇼피파이 ショッピファイ Shopify ショピファイ',
  'COIN': '코인베이스 コインベース Coinbase 加密货币 加密貨幣',
  'MSTR': '마이크로스트래티지 マイクロストラテジー 微策略 Микростратеги',
  'HOOD': '로빈후드 ロビンフッド Robinhood 罗宾汉 羅賓漢',
  'BTC': '비트코인 ビットコイン 比特币 比特幣 Биткоин',
};

const Map<String, List<String>> _chartSearchTermExpansions = {
  '애플': ['apple', 'aapl'],
  'アップル': ['apple', 'aapl'],
  '苹果': ['apple', 'aapl'],
  '蘋果': ['apple', 'aapl'],
  'манзана': ['apple', 'aapl'],
  '마이크로소프트': ['microsoft', 'msft'],
  'マイクロソフト': ['microsoft', 'msft'],
  '微软': ['microsoft', 'msft'],
  '微軟': ['microsoft', 'msft'],
  'майкрософт': ['microsoft', 'msft'],
  '엔비디아': ['nvidia', 'nvda'],
  'エヌビディア': ['nvidia', 'nvda'],
  '英伟达': ['nvidia', 'nvda'],
  '輝達': ['nvidia', 'nvda'],
  '아마존': ['amazon', 'amzn'],
  'アマゾン': ['amazon', 'amzn'],
  '亚马逊': ['amazon', 'amzn'],
  '亞馬遜': ['amazon', 'amzn'],
  '구글': ['google', 'alphabet', 'googl', 'goog'],
  '알파벳': ['alphabet', 'google', 'googl', 'goog'],
  'グーグル': ['google', 'alphabet', 'googl', 'goog'],
  '谷歌': ['google', 'alphabet', 'googl', 'goog'],
  '메타': ['meta', 'facebook'],
  '페이스북': ['meta', 'facebook'],
  'フェイスブック': ['meta', 'facebook'],
  '脸书': ['meta', 'facebook'],
  '臉書': ['meta', 'facebook'],
  '테슬라': ['tesla', 'tsla'],
  'テスラ': ['tesla', 'tsla'],
  '特斯拉': ['tesla', 'tsla'],
  '브로드컴': ['broadcom', 'avgo'],
  '博通': ['broadcom', 'avgo'],
  '버크셔': ['berkshire', 'brk b'],
  '해서웨이': ['hathaway', 'brk b'],
  '伯克希尔': ['berkshire', 'brk b'],
  '波克夏': ['berkshire', 'brk b'],
  '일라이릴리': ['eli lilly', 'lly'],
  '릴리': ['eli lilly', 'lly'],
  '礼来': ['eli lilly', 'lly'],
  '禮來': ['eli lilly', 'lly'],
  '제이피모건': ['jpmorgan', 'jpm'],
  'jp모건': ['jpmorgan', 'jpm'],
  '摩根大通': ['jpmorgan', 'jpm'],
  '비자': ['visa', 'v'],
  '维萨': ['visa', 'v'],
  '維薩': ['visa', 'v'],
  '마스터카드': ['mastercard', 'ma'],
  '万事达': ['mastercard', 'ma'],
  '萬事達': ['mastercard', 'ma'],
  '유나이티드헬스': ['unitedhealth', 'unh'],
  '联合健康': ['unitedhealth', 'unh'],
  '聯合健康': ['unitedhealth', 'unh'],
  '엑슨모빌': ['exxon mobil', 'xom'],
  '엑손모빌': ['exxon mobil', 'xom'],
  '埃克森美孚': ['exxon mobil', 'xom'],
  '코스트코': ['costco', 'cost'],
  '好市多': ['costco', 'cost'],
  '홈디포': ['home depot', 'hd'],
  '家得宝': ['home depot', 'hd'],
  '家得寶': ['home depot', 'hd'],
  '넷플릭스': ['netflix', 'nflx'],
  '奈飞': ['netflix', 'nflx'],
  '奈飛': ['netflix', 'nflx'],
  '월마트': ['walmart', 'wmt'],
  '沃尔玛': ['walmart', 'wmt'],
  '沃爾瑪': ['walmart', 'wmt'],
  '오라클': ['oracle', 'orcl'],
  '甲骨文': ['oracle', 'orcl'],
  '코카콜라': ['coca cola', 'ko'],
  '可口可乐': ['coca cola', 'ko'],
  '可口可樂': ['coca cola', 'ko'],
  '셰브론': ['chevron', 'cvx'],
  '쉐브론': ['chevron', 'cvx'],
  '雪佛龙': ['chevron', 'cvx'],
  '에이엠디': ['amd'],
  '超微': ['amd'],
  '시스코': ['cisco', 'csco'],
  '思科': ['cisco', 'csco'],
  '맥도날드': ['mcdonalds', 'mcd'],
  '麦当劳': ['mcdonalds', 'mcd'],
  '펩시': ['pepsico', 'pep'],
  '百事': ['pepsico', 'pep'],
  '디즈니': ['disney', 'dis'],
  '迪士尼': ['disney', 'dis'],
  '우버': ['uber'],
  '优步': ['uber'],
  '優步': ['uber'],
  '스타벅스': ['starbucks', 'sbux'],
  '星巴克': ['starbucks', 'sbux'],
  '팔란티어': ['palantir', 'pltr'],
  '帕兰提尔': ['palantir', 'pltr'],
  '帕蘭提爾': ['palantir', 'pltr'],
  '쇼피파이': ['shopify', 'shop'],
  '코인베이스': ['coinbase', 'coin'],
  '로빈후드': ['robinhood', 'hood'],
  '삼성전자': ['samsung electronics', '005930'],
  '삼성': ['samsung electronics', '005930'],
  'サムスン': ['samsung electronics', '005930'],
  '三星电子': ['samsung electronics', '005930'],
  '三星電子': ['samsung electronics', '005930'],
  '하이닉스': ['sk hynix', '000660'],
  'sk하이닉스': ['sk hynix', '000660'],
  '海力士': ['sk hynix', '000660'],
  '현대차': ['hyundai motor', '005380'],
  '현대자동차': ['hyundai motor', '005380'],
  '现代': ['hyundai motor', '005380'],
  '現代': ['hyundai motor', '005380'],
  '네이버': ['naver', '035420'],
  '카카오': ['kakao', '035720'],
  'lg화학': ['lg chem', '051910'],
  '엘지화학': ['lg chem', '051910'],
  'lg에너지솔루션': ['lg energy solution', '373220'],
  '엘지에너지솔루션': ['lg energy solution', '373220'],
  'tsmc': ['taiwan semiconductor', 'tsm'],
  '台積電': ['tsmc', 'taiwan semiconductor', 'tsm'],
  '台积电': ['tsmc', 'taiwan semiconductor', 'tsm'],
  '티에스엠씨': ['tsmc', 'taiwan semiconductor', 'tsm'],
  '텐센트': ['tencent', '0700'],
  '腾讯': ['tencent', '0700'],
  '騰訊': ['tencent', '0700'],
  '알리바바': ['alibaba', '9988', 'baba'],
  '阿里巴巴': ['alibaba', '9988', 'baba'],
  '토요타': ['toyota', '7203'],
  '도요타': ['toyota', '7203'],
  '丰田': ['toyota', '7203'],
  '豐田': ['toyota', '7203'],
  '소니': ['sony', '6758'],
  '索尼': ['sony', '6758'],
  '소프트뱅크': ['softbank', '9984'],
  'ソフトバンク': ['softbank', '9984'],
  '비야디': ['byd', '1211'],
  '比亚迪': ['byd', '1211'],
  '比亞迪': ['byd', '1211'],
  '아이온큐': ['ionq', 'quantum computing'],
  '이온큐': ['ionq', 'quantum computing'],
  '퀀텀컴퓨팅': ['quantum computing', 'ionq', 'rgti', 'qubt', 'qbts', 'qtum'],
  '양자컴퓨터': ['quantum computing'],
  '양자컴퓨팅': ['quantum computing'],
  '量子计算': ['quantum computing'],
  '量子運算': ['quantum computing'],
  'computación cuántica': ['quantum computing'],
  'computação quântica': ['quantum computing'],
  'informatique quantique': ['quantum computing'],
  'quantencomputing': ['quantum computing'],
  'квантовые вычисления': ['quantum computing'],
  '반도체': ['semiconductor'],
  '半導体': ['semiconductor'],
  '半导体': ['semiconductor'],
  '半導體': ['semiconductor'],
  'semiconductor': ['semiconductor'],
  'semiconductores': ['semiconductor'],
  'semi condutores': ['semiconductor'],
  'semi conducteurs': ['semiconductor'],
  'halbleiter': ['semiconductor'],
  'полупроводник': ['semiconductor'],
  '전기차': ['ev', 'electric vehicle'],
  '전기 자동차': ['ev', 'electric vehicle'],
  '電気自動車': ['ev', 'electric vehicle'],
  '电动车': ['ev', 'electric vehicle'],
  '電動車': ['ev', 'electric vehicle'],
  'coche eléctrico': ['ev', 'electric vehicle'],
  'carro elétrico': ['ev', 'electric vehicle'],
  'voiture électrique': ['ev', 'electric vehicle'],
  'elektroauto': ['ev', 'electric vehicle'],
  'электромобиль': ['ev', 'electric vehicle'],
  '은행': ['bank'],
  '銀行': ['bank'],
  '银行': ['bank'],
  'banco': ['bank'],
  'banque': ['bank'],
  'банк': ['bank'],
  '보험': ['insurance'],
  '保险': ['insurance'],
  '保險': ['insurance'],
  'seguro': ['insurance'],
  'assurance': ['insurance'],
  'versicherung': ['insurance'],
  'страхование': ['insurance'],
  '제약': ['pharma', 'pharmaceutical'],
  '医薬': ['pharma', 'pharmaceutical'],
  '制药': ['pharma', 'pharmaceutical'],
  '製藥': ['pharma', 'pharmaceutical'],
  'farmacéutica': ['pharma', 'pharmaceutical'],
  'farmaceutica': ['pharma', 'pharmaceutical'],
  'pharmaceutique': ['pharma', 'pharmaceutical'],
  'pharmazeutik': ['pharma', 'pharmaceutical'],
  'фармацевтика': ['pharma', 'pharmaceutical'],
  '바이오': ['biotech', 'bio'],
  '生物科技': ['biotech', 'bio'],
  'biotecnología': ['biotech', 'bio'],
  'biotecnologia': ['biotech', 'bio'],
  'biotechnologie': ['biotech', 'bio'],
  'биотехнологии': ['biotech', 'bio'],
  '에너지': ['energy'],
  'エネルギー': ['energy'],
  '能源': ['energy'],
  'energía': ['energy'],
  'energia': ['energy'],
  'énergie': ['energy'],
  'энергия': ['energy'],
  '석유': ['oil', 'crude'],
  '원유': ['oil', 'crude'],
  '石油': ['oil', 'crude'],
  'petróleo': ['oil', 'crude'],
  'petroleo': ['oil', 'crude'],
  'pétrole': ['oil', 'crude'],
  'нефть': ['oil', 'crude'],
  '천연가스': ['natural gas'],
  '天然气': ['natural gas'],
  '天然氣': ['natural gas'],
  'gas natural': ['natural gas'],
  'gaz naturel': ['natural gas'],
  'erdgas': ['natural gas'],
  'природный газ': ['natural gas'],
  '금': ['gold'],
  '골드': ['gold'],
  'ゴールド': ['gold'],
  '黄金': ['gold'],
  '黃金': ['gold'],
  'oro': ['gold'],
  'ouro': ['gold'],
  'золото': ['gold'],
  '은': ['silver'],
  '실버': ['silver'],
  'シルバー': ['silver'],
  '白银': ['silver'],
  '白銀': ['silver'],
  'plata': ['silver'],
  'prata': ['silver'],
  'argent': ['silver'],
  'серебро': ['silver'],
  '구리': ['copper'],
  '동': ['copper'],
  '銅': ['copper'],
  '铜': ['copper'],
  'cobre': ['copper'],
  'cuivre': ['copper'],
  'медь': ['copper'],
  'kupfer': ['copper'],
  '비트코인': ['bitcoin', 'btc'],
  'ビットコイン': ['bitcoin', 'btc'],
  '比特币': ['bitcoin', 'btc'],
  '比特幣': ['bitcoin', 'btc'],
  'биткоин': ['bitcoin', 'btc'],
  '이더리움': ['ethereum', 'eth'],
  'イーサリアム': ['ethereum', 'eth'],
  '以太坊': ['ethereum', 'eth'],
  'эфир': ['ethereum', 'eth'],
  '나스닥': ['nasdaq'],
  'ナスダック': ['nasdaq'],
  '纳斯达克': ['nasdaq'],
  '納斯達克': ['nasdaq'],
  '코스피': ['kospi'],
  '니케이': ['nikkei'],
  '닛케이': ['nikkei'],
  '日経': ['nikkei'],
  '중국지수': ['sse composite', 'china'],
  '상해종합': ['sse composite', 'china'],
  '上海综合': ['sse composite', 'china'],
  '上海綜合': ['sse composite', 'china'],
  '대만지수': ['taiex', 'taiwan'],
  '독일지수': ['dax', 'germany'],
  '프랑스지수': ['cac', 'france'],
  '스페인지수': ['ibex', 'spain'],
  '포르투갈지수': ['psi', 'portugal'],
  '러시아지수': ['moex', 'russia'],
  '아이셰어즈': ['ishares'],
  'アイシェアーズ': ['ishares'],
  '安硕': ['ishares'],
  '安碩': ['ishares'],
  '뱅가드': ['vanguard'],
  'バンガード': ['vanguard'],
  '先锋': ['vanguard'],
  '先鋒': ['vanguard'],
  '프로셰어즈': ['proshares'],
  'プロシェアーズ': ['proshares'],
  '디렉시온': ['direxion'],
  'ディレクション': ['direxion'],
  '반에크': ['vaneck'],
  'ヴァンエック': ['vaneck'],
  '아크': ['ark'],
  'アーク': ['ark'],
  '슈왑': ['schwab'],
  'シュワブ': ['schwab'],
  '스파이더': ['spdr'],
  '스테이트스트리트': ['spdr', 'state street'],
  '에스피디알': ['spdr'],
};

const Map<String, List<String>> _localizedChartKeywordAliases = {
  'technology': [
    '기술',
    '테크',
    'テクノロジー',
    '科技',
    'tecnologia',
    'technologie',
    'Technologie',
    'технологии'
  ],
  'software': [
    '소프트웨어',
    'ソフトウェア',
    '软件',
    '軟體',
    'software',
    'logiciel',
    'Software',
    'программное обеспечение'
  ],
  'cloud': [
    '클라우드',
    'クラウド',
    '云',
    '雲',
    'nube',
    'nuvem',
    'nuage',
    'Cloud',
    'облако'
  ],
  'data': [
    '데이터',
    'データ',
    '数据',
    '數據',
    'datos',
    'dados',
    'données',
    'Daten',
    'данные'
  ],
  'artificial intelligence': [
    '인공지능',
    '人工知能',
    '人工智能',
    'ia',
    'inteligencia artificial',
    'intelligence artificielle',
    'künstliche intelligenz',
    'искусственный интеллект'
  ],
  'ai': [
    '인공지능',
    '人工知能',
    '人工智能',
    'ia',
    'inteligencia artificial',
    'intelligence artificielle',
    'ki',
    'ии'
  ],
  'semiconductor': [
    '반도체',
    '半導体',
    '半导体',
    '半導體',
    'semiconductor',
    'semiconductores',
    'semi condutores',
    'semi-conducteur',
    'Halbleiter',
    'полупроводник'
  ],
  'chip': ['반도체', '칩', 'チップ', '芯片', '晶片', 'chip', 'puce', 'Halbleiter'],
  'network': [
    '네트워크',
    'ネットワーク',
    '网络',
    '網路',
    'red',
    'rede',
    'réseau',
    'Netzwerk',
    'сеть'
  ],
  'cybersecurity': [
    '사이버보안',
    '보안',
    'サイバーセキュリティ',
    '网络安全',
    '網路安全',
    'ciberseguridad',
    'ciberseguranca',
    'cybersécurité',
    'Cybersicherheit',
    'кибербезопасность'
  ],
  'security': [
    '보안',
    'セキュリティ',
    '安全',
    'seguridad',
    'segurança',
    'sécurité',
    'Sicherheit',
    'безопасность'
  ],
  'communication': [
    '통신',
    '通信',
    'telecomunicaciones',
    'telecomunicações',
    'télécom',
    'Telekommunikation',
    'связь'
  ],
  'telecom': [
    '통신',
    '通信',
    'telecomunicaciones',
    'telecomunicações',
    'télécom',
    'Telekommunikation',
    'связь'
  ],
  'media': [
    '미디어',
    'メディア',
    '媒体',
    'medios',
    'mídia',
    'médias',
    'Medien',
    'медиа'
  ],
  'streaming': [
    '스트리밍',
    '動画配信',
    '流媒体',
    '串流',
    'streaming',
    'transmisión',
    'streamen'
  ],
  'game': ['게임', 'ゲーム', '游戏', '遊戲', 'juego', 'jogo', 'jeu', 'Spiel', 'игра'],
  'gaming': ['게임', 'ゲーム', '游戏', '遊戲', 'juego', 'jogo', 'jeu', 'Spiel', 'игры'],
  'ecommerce': [
    '이커머스',
    '전자상거래',
    '電子商取引',
    '电子商务',
    '電子商務',
    'comercio electrónico',
    'comércio eletrônico',
    'commerce électronique',
    'E-Commerce',
    'электронная коммерция'
  ],
  'commerce': [
    '상거래',
    '商取引',
    '商务',
    '商務',
    'comercio',
    'comércio',
    'commerce',
    'Handel',
    'торговля'
  ],
  'retail': [
    '리테일',
    '소매',
    '小売',
    '零售',
    'minorista',
    'varejo',
    'détail',
    'Einzelhandel',
    'розница'
  ],
  'consumer': [
    '소비재',
    '소비자',
    '消費者',
    '消费',
    '消費',
    'consumo',
    'consommateur',
    'Verbraucher',
    'потребитель'
  ],
  'beverage': ['음료', '飲料', '饮料', 'bebida', 'boisson', 'Getränk', 'напитки'],
  'food': [
    '식품',
    '음식',
    '食品',
    '食物',
    'alimentos',
    'comida',
    'nourriture',
    'Lebensmittel',
    'еда'
  ],
  'restaurant': [
    '레스토랑',
    '음식점',
    'レストラン',
    '餐厅',
    '餐廳',
    'restaurante',
    'restaurant',
    'ресторан'
  ],
  'travel': [
    '여행',
    '旅行',
    '旅游',
    '旅遊',
    'viaje',
    'viagem',
    'voyage',
    'Reise',
    'путешествие'
  ],
  'hotel': ['호텔', 'ホテル', '酒店', '旅館', 'hotel', 'hôtel', 'отель'],
  'bank': ['은행', '銀行', '银行', 'banco', 'banque', 'Bank', 'банк'],
  'financial': [
    '금융',
    '金融',
    'financiero',
    'financeiro',
    'financier',
    'Finanzen',
    'финансы'
  ],
  'finance': [
    '금융',
    '金融',
    'finanzas',
    'finanças',
    'finance',
    'Finanzen',
    'финансы'
  ],
  'fintech': ['핀테크', 'フィンテック', '金融科技', 'fintech', 'финтех'],
  'payment': [
    '결제',
    '支払い',
    '支付',
    'pago',
    'pagamento',
    'paiement',
    'Zahlung',
    'платеж'
  ],
  'insurance': [
    '보험',
    '保険',
    '保险',
    '保險',
    'seguro',
    'assurance',
    'Versicherung',
    'страхование'
  ],
  'brokerage': [
    '증권',
    '브로커리지',
    '証券',
    '证券',
    '證券',
    'corretaje',
    'courtage',
    'Brokerage',
    'брокер'
  ],
  'asset': [
    '자산',
    '資産',
    '资产',
    '資產',
    'activo',
    'ativo',
    'actif',
    'Vermögen',
    'актив'
  ],
  'health': [
    '헬스케어',
    '건강',
    'ヘルスケア',
    '健康',
    'salud',
    'saúde',
    'santé',
    'Gesundheit',
    'здоровье'
  ],
  'healthcare': [
    '헬스케어',
    '의료',
    'ヘルスケア',
    '医疗',
    '醫療',
    'salud',
    'saúde',
    'santé',
    'Gesundheit',
    'здравоохранение'
  ],
  'pharma': [
    '제약',
    '製薬',
    '制药',
    '製藥',
    'farmacéutica',
    'farmaceutica',
    'pharmaceutique',
    'Pharma',
    'фармацевтика'
  ],
  'pharmaceutical': [
    '제약',
    '製薬',
    '制药',
    '製藥',
    'farmacéutica',
    'farmaceutica',
    'pharmaceutique',
    'Pharma',
    'фармацевтика'
  ],
  'biotech': [
    '바이오',
    '바이오테크',
    'バイオ',
    '生物科技',
    'biotecnología',
    'biotecnologia',
    'biotechnologie',
    'Biotechnologie',
    'биотехнологии'
  ],
  'medical': [
    '의료',
    '医療',
    '医疗',
    '醫療',
    'médico',
    'medico',
    'médical',
    'medizinisch',
    'медицина'
  ],
  'energy': [
    '에너지',
    'エネルギー',
    '能源',
    'energía',
    'energia',
    'énergie',
    'Energie',
    'энергия'
  ],
  'oil': [
    '석유',
    '원유',
    'オイル',
    '石油',
    'petróleo',
    'petroleo',
    'pétrole',
    'Öl',
    'нефть'
  ],
  'gas': ['가스', 'ガス', '天然气', '天然氣', 'gas', 'gaz', 'Gas', 'газ'],
  'natural gas': [
    '천연가스',
    '天然气',
    '天然氣',
    'gas natural',
    'gaz naturel',
    'Erdgas',
    'природный газ'
  ],
  'nuclear': [
    '원전',
    '원자력',
    '原子力',
    '核能',
    'nuclear',
    'nucléaire',
    'Kernenergie',
    'ядерная энергетика'
  ],
  'uranium': ['우라늄', 'ウラン', '铀', '鈾', 'uranio', 'uranium', 'Uran', 'уран'],
  'utility': [
    '유틸리티',
    '전력',
    '公益',
    '公用事业',
    '公用事業',
    'servicios públicos',
    'utilidade',
    'services publics',
    'Versorger',
    'коммунальные услуги'
  ],
  'power': [
    '전력',
    '파워',
    '電力',
    '电力',
    'poder',
    'energia',
    'puissance',
    'Strom',
    'энергия'
  ],
  'electric': [
    '전기',
    '電気',
    '电力',
    '電力',
    'eléctrico',
    'elétrico',
    'électrique',
    'elektrisch',
    'электрический'
  ],
  'industrial': [
    '산업재',
    '산업',
    '工業',
    '工业',
    'industrial',
    'industrie',
    'Industrie',
    'промышленность'
  ],
  'infrastructure': [
    '인프라',
    'インフラ',
    '基础设施',
    '基礎設施',
    'infraestructura',
    'infraestrutura',
    'infrastructure',
    'Infrastruktur',
    'инфраструктура'
  ],
  'construction': [
    '건설',
    '建設',
    '建筑',
    '建築',
    'construcción',
    'construção',
    'construction',
    'Bau',
    'строительство'
  ],
  'materials': [
    '소재',
    '재료',
    '材料',
    'materiales',
    'materiais',
    'matériaux',
    'Materialien',
    'материалы'
  ],
  'chemical': [
    '화학',
    '化学',
    '化工',
    'química',
    'quimica',
    'chimie',
    'Chemie',
    'химия'
  ],
  'mining': [
    '광산',
    '채굴',
    '鉱業',
    '矿业',
    '礦業',
    'minería',
    'mineração',
    'mine',
    'Bergbau',
    'добыча'
  ],
  'gold': [
    '금',
    '골드',
    'ゴールド',
    '黄金',
    '黃金',
    'oro',
    'ouro',
    'or',
    'Gold',
    'золото'
  ],
  'silver': [
    '은',
    '실버',
    'シルバー',
    '白银',
    '白銀',
    'plata',
    'prata',
    'argent',
    'Silber',
    'серебро'
  ],
  'copper': ['구리', '동', '銅', '铜', 'cobre', 'cuivre', 'Kupfer', 'медь'],
  'automotive': [
    '자동차',
    '自動車',
    '汽车',
    '汽車',
    'automóvil',
    'automóvel',
    'automobile',
    'Auto',
    'автомобиль'
  ],
  'auto': [
    '자동차',
    '自動車',
    '汽车',
    '汽車',
    'auto',
    'coche',
    'carro',
    'voiture',
    'Auto',
    'авто'
  ],
  'ev': [
    '전기차',
    '電気自動車',
    '电动车',
    '電動車',
    'coche eléctrico',
    'carro elétrico',
    'voiture électrique',
    'Elektroauto',
    'электромобиль'
  ],
  'electric vehicle': [
    '전기차',
    '電気自動車',
    '电动车',
    '電動車',
    'coche eléctrico',
    'carro elétrico',
    'voiture électrique',
    'Elektroauto',
    'электромобиль'
  ],
  'battery': [
    '배터리',
    '電池',
    '电池',
    'batería',
    'bateria',
    'batterie',
    'Batterie',
    'аккумулятор'
  ],
  'lithium': [
    '리튬',
    'リチウム',
    '锂',
    '鋰',
    'litio',
    'lítio',
    'lithium',
    'Lithium',
    'литий'
  ],
  'robot': [
    '로봇',
    'ロボット',
    '机器人',
    '機器人',
    'robot',
    'robótica',
    'robotique',
    'Roboter',
    'робот'
  ],
  'robotics': [
    '로봇',
    '로보틱스',
    'ロボティクス',
    '机器人',
    '機器人',
    'robótica',
    'robotique',
    'Robotik',
    'робототехника'
  ],
  'automation': [
    '자동화',
    '自動化',
    '自动化',
    '自動化',
    'automatización',
    'automação',
    'automatisation',
    'Automatisierung',
    'автоматизация'
  ],
  'quantum': [
    '양자',
    '퀀텀',
    '量子',
    'quantique',
    'quântico',
    'cuántico',
    'Quanten',
    'квантовый'
  ],
  'space': ['우주', '宇宙', 'espacio', 'espaço', 'espace', 'Weltraum', 'космос'],
  'aerospace': [
    '항공우주',
    '航空宇宙',
    '航天',
    'aeroespacial',
    'aeroespacial',
    'aérospatial',
    'Luft Raumfahrt',
    'аэрокосмический'
  ],
  'aviation': [
    '항공',
    '航空',
    'aviación',
    'aviação',
    'aviation',
    'Luftfahrt',
    'авиация'
  ],
  'defense': [
    '방산',
    '방위',
    '防衛',
    '国防',
    '國防',
    'defensa',
    'defesa',
    'défense',
    'Verteidigung',
    'оборона'
  ],
  'railroad': [
    '철도',
    '鉄道',
    '铁路',
    '鐵路',
    'ferrocarril',
    'ferrovia',
    'chemin de fer',
    'Eisenbahn',
    'железная дорога'
  ],
  'shipping': [
    '운송',
    '해운',
    '配送',
    '运输',
    '運輸',
    'envío',
    'transporte',
    'expédition',
    'Versand',
    'доставка'
  ],
  'delivery': [
    '배달',
    '배송',
    '配達',
    '外卖',
    '外賣',
    'entrega',
    'livraison',
    'Lieferung',
    'доставка'
  ],
  'logistics': ['물류', '物流', 'logística', 'logistique', 'Logistik', 'логистика'],
  'etf': [
    'ETF',
    '상장지수펀드',
    '上場投資信託',
    '交易所交易基金',
    'fondo cotizado',
    'fonds négocié',
    'börsengehandelter fonds'
  ],
  'bond': [
    '채권',
    '債券',
    '债券',
    'bono',
    'título',
    'obligation',
    'Anleihe',
    'облигация'
  ],
  'treasury': [
    '국채',
    '米国債',
    '美国国债',
    '美國國債',
    'tesoro',
    'tesouro',
    'trésor',
    'Staatsanleihe',
    'казначейство'
  ],
  'dividend': [
    '배당',
    '配当',
    '股息',
    'dividendo',
    'dividende',
    'Dividende',
    'дивиденд'
  ],
  'covered call': [
    '커버드콜',
    'カバードコール',
    '备兑看涨',
    '備兌買權',
    'call cubierta',
    'call coberta',
    'appel couvert'
  ],
  'leveraged': [
    '레버리지',
    'レバレッジ',
    '杠杆',
    '槓桿',
    'apalancado',
    'alavancado',
    'effet de levier',
    'gehebelt',
    'кредитное плечо'
  ],
  'inverse': [
    '인버스',
    '역방향',
    'インバース',
    '反向',
    'inverso',
    'inverse',
    'umgekehrt',
    'обратный'
  ],
  'bitcoin': ['비트코인', 'ビットコイン', '比特币', '比特幣', 'bitcoin', 'биткоин'],
  'ethereum': ['이더리움', 'イーサリアム', '以太坊', 'ethereum', 'эфир'],
  'crypto': [
    '코인',
    '암호화폐',
    '暗号資産',
    '加密货币',
    '加密貨幣',
    'cripto',
    'cryptomonnaie',
    'Krypto',
    'криптовалюта'
  ],
  'defi': [
    '디파이',
    '분산금융',
    'DeFi',
    '去中心化金融',
    'finanzas descentralizadas',
    'finance décentralisée'
  ],
  'stablecoin': [
    '스테이블코인',
    'ステーブルコイン',
    '稳定币',
    '穩定幣',
    'moneda estable',
    'stablecoin'
  ],
  'index': ['지수', '指数', '指數', 'índice', 'indice', 'Index', 'индекс'],
  'volatility': [
    '변동성',
    'ボラティリティ',
    '波动率',
    '波動率',
    'volatilidad',
    'volatilidade',
    'volatilité',
    'Volatilität',
    'волатильность'
  ],
  'yield': [
    '금리',
    '수익률',
    '利回り',
    '收益率',
    'rendimiento',
    'rendimento',
    'rendement',
    'Rendite',
    'доходность'
  ],
};

const Map<String, List<String>> _exchangeSearchInfo = {
  'usdIndex': ['DXY', 'US Dollar Index', '달러 인덱스 미국 달러'],
  'usdKrw': ['KRW', 'South Korea', '원화 한국 원 달러원 달러/원 won korea'],
  'usdJpy': ['JPY', 'Japan', '엔화 일본 엔 달러엔 달러/엔 yen japan'],
  'eurUsd': ['EUR', 'Eurozone', '유로 유럽 스페인 포르투갈 프랑스 독일 euro'],
  'usdRub': ['RUB', 'Russia', '루블 러시아 ruble'],
  'usdTwd': ['TWD', 'Taiwan', '대만 달러 타이완'],
  'usdCny': ['CNY', 'China', '위안 중국 위안화'],
  'btcUsd': ['BTC', 'Bitcoin', '비트코인 bitcoin'],
  'usdGbp': ['GBP', 'United Kingdom', '파운드 영국 pound'],
  'usdCad': ['CAD', 'Canada', '캐나다 달러'],
  'usdAud': ['AUD', 'Australia', '호주 달러 오스트레일리아'],
  'usdNzd': ['NZD', 'New Zealand', '뉴질랜드 달러'],
  'usdChf': ['CHF', 'Switzerland', '스위스 프랑'],
  'usdSek': ['SEK', 'Sweden', '스웨덴 크로나'],
  'usdNok': ['NOK', 'Norway', '노르웨이 크로네'],
  'usdDkk': ['DKK', 'Denmark', '덴마크 크로네'],
  'usdPln': ['PLN', 'Poland', '폴란드 즈워티'],
  'usdCzk': ['CZK', 'Czech Republic', '체코 코루나'],
  'usdHuf': ['HUF', 'Hungary', '헝가리 포린트'],
  'usdTry': ['TRY', 'Turkey', '튀르키예 터키 리라'],
  'usdMxn': ['MXN', 'Mexico', '멕시코 페소'],
  'usdBrl': ['BRL', 'Brazil', '브라질 헤알'],
  'usdArs': ['ARS', 'Argentina', '아르헨티나 페소'],
  'usdClp': ['CLP', 'Chile', '칠레 페소'],
  'usdCop': ['COP', 'Colombia', '콜롬비아 페소'],
  'usdPen': ['PEN', 'Peru', '페루 솔'],
  'usdZar': ['ZAR', 'South Africa', '남아공 남아프리카 랜드'],
  'usdEgp': ['EGP', 'Egypt', '이집트 파운드'],
  'usdSar': ['SAR', 'Saudi Arabia', '사우디 리얄'],
  'usdAed': ['AED', 'United Arab Emirates', '아랍에미리트 UAE 디르함'],
  'usdQar': ['QAR', 'Qatar', '카타르 리얄'],
  'usdKwd': ['KWD', 'Kuwait', '쿠웨이트 디나르'],
  'usdIls': ['ILS', 'Israel', '이스라엘 셰켈'],
  'usdInr': ['INR', 'India', '인도 루피'],
  'usdIdr': ['IDR', 'Indonesia', '인도네시아 루피아'],
  'usdThb': ['THB', 'Thailand', '태국 바트'],
  'usdVnd': ['VND', 'Vietnam', '베트남 동'],
  'usdPhp': ['PHP', 'Philippines', '필리핀 페소'],
  'usdMyr': ['MYR', 'Malaysia', '말레이시아 링깃'],
  'usdSgd': ['SGD', 'Singapore', '싱가포르 달러'],
  'usdHkd': ['HKD', 'Hong Kong', '홍콩 달러'],
  'usdPkr': ['PKR', 'Pakistan', '파키스탄 루피'],
  'usdBdt': ['BDT', 'Bangladesh', '방글라데시 타카'],
  'usdLkr': ['LKR', 'Sri Lanka', '스리랑카 루피'],
  'usdKzt': ['KZT', 'Kazakhstan', '카자흐스탄 텡게'],
  'usdUah': ['UAH', 'Ukraine', '우크라이나 흐리우냐'],
  'usdRon': ['RON', 'Romania', '루마니아 레우'],
  'usdBgn': ['BGN', 'Bulgaria', '불가리아 레프'],
  'usdIsk': ['ISK', 'Iceland', '아이슬란드 크로나'],
  'usdMad': ['MAD', 'Morocco', '모로코 디르함'],
  'usdNgn': ['NGN', 'Nigeria', '나이지리아 나이라'],
  'usdKes': ['KES', 'Kenya', '케냐 실링'],
};

const Map<String, String> _chartUniversalSearchAliases = {
  'GOOG': '구글 알파벳 グーグル アルファベット 谷歌 字母表 Google Alphabet',
  'ASML': '에이에스엠엘 ASML 반도체 半導体 半导体 半導體 semiconductor',
  'INTC': '인텔 インテル 英特尔 英特爾 Intel',
  'ARM': '암 ARM アーム 安谋 安謀 반도체 semiconductor',
  'TMUS': '티모바일 T모바일 T-Mobile ティーモバイル 电信 電信 통신 telecom',
  'STX': '씨게이트 시게이트 Seagate シーゲイト 希捷 하드디스크 storage',
  'MRVL': '마벨 Marvell マーベル 美满 美滿 반도체 semiconductor',
  'WDC': '웨스턴디지털 Western Digital ウエスタンデジタル 西部数据 storage',
  'CRWD': '크라우드스트라이크 CrowdStrike クラウドストライク 网络安全 사이버보안 security',
  'PDD': '핀둬둬 테무 PDD 拼多多 Temu 전자상거래 ecommerce',
  'CEG': '컨스텔레이션 에너지 Constellation Energy 原子力 에너지 energy',
  'CDNS': '케이던스 Cadence ケイデンス 반도체 설계 EDA semiconductor',
  'SNPS': '시놉시스 Synopsys シノプシス 반도체 설계 EDA semiconductor',
  'MAR': '메리어트 Marriott マリオット 万豪 호텔 hotel',
  'FTNT': '포티넷 Fortinet フォーティネット 飞塔 飛塔 보안 security',
  'CSX': 'CSX 철도 railroad 铁路 鐵路',
  'MNST': '몬스터 Monster Beverage モンスター 饮料 飲料 음료',
  'NXPI': 'NXP 엔엑스피 半导体 半導體 반도체 semiconductor',
  'MPWR': '모놀리식 파워 Monolithic Power 电源 電源 반도체 semiconductor',
  'DDOG': '데이터독 Datadog データドッグ 云监控 雲監控 클라우드 모니터링',
  'ROST': '로스스토어 Ross Stores ロスストア 折扣零售 소매 retail',
  'ORLY': '오라일리 OReilly オライリー 자동차부품 auto parts',
  'AEP': '아메리칸 일렉트릭 파워 American Electric Power 전력 utility',
  'CTAS': '신타스 Cintas シンタス 유니폼 uniform',
  'WBD': '워너브라더스 Warner Bros Discovery ワーナー 미디어 media',
  'DASH': '도어대시 DoorDash ドアダッシュ 外卖 外賣 배달 delivery',
  'BKR': '베이커휴즈 Baker Hughes ベーカーヒューズ 油田 에너지 energy',
  'PCAR': '파카 PACCAR パッカー 트럭 truck',
  'FANG': '다이아몬드백 에너지 Diamondback Energy 석유 oil energy',
  'MCHP': '마이크로칩 Microchip マイクロチップ 반도체 semiconductor',
  'FAST': '패스널 Fastenal ファスナル 산업재 industrial',
  'EA': '일렉트로닉아츠 EA エレクトロニックアーツ 游戏 遊戲 게임',
  'XEL': '엑셀 에너지 Xcel Energy 전력 utility',
  'ADSK': '오토데스크 Autodesk オートデスク 设计 設計 설계 software',
  'FER': '페로비알 Ferrovial インフラ 基础设施 基礎設施 infrastructure',
  'EXC': '엑셀론 Exelon エクセロン 전력 utility',
  'ODFL': '올드도미니언 Old Dominion Freight 物流 운송 transport',
  'IDXX': '아이덱스 IDEXX 動物 医療 동물 의료 veterinary',
  'CCEP': '코카콜라 유로퍼시픽 Coca-Cola Europacific 음료 beverage',
  'TTWO': '테이크투 Take Two テイクツー 游戏 遊戲 게임',
  'KDP': '큐리그 닥터페퍼 Keurig Dr Pepper 饮料 飲料 음료',
  'ALNY': '앨나일람 Alnylam アルナイラム 바이오 bio biotech',
  'PYPL': '페이팔 PayPal ペイパル 支付 결제 payment',
  'TRI': '톰슨로이터 Thomson Reuters トムソンロイター 정보 data',
  'PAYX': '페이첵스 Paychex ペイチェックス 급여 payroll',
  'ROP': '로퍼 Roper Technologies ローパー 산업기술 technology',
  'CPRT': '코파트 Copart コパート 경매 auction',
  'AXON': '액손 Axon アクソン 경찰 장비 taser',
  'WDAY': '워크데이 Workday ワークデイ 인사 HR software',
  'ZS': '지스케일러 Zscaler ゼットスケーラー 보안 security',
  'GEHC': 'GE헬스케어 GE HealthCare 医療 헬스케어 healthcare',
  'KHC': '크래프트하인즈 Kraft Heinz 食品 식품 food',
  'DXCM': '덱스컴 DexCom デックスコム 당뇨 diabetes healthcare',
  'CTSH': '코그니전트 Cognizant コグニザント IT 서비스 service',
  'INSM': '인스메드 Insmed インスメッド 바이오 biotech',
  'VRSK': '베리스크 Verisk ベリスク 데이터 data analytics',
  'TEAM': '아틀라시안 Atlassian アトラシアン 협업 software',
  'CHTR': '차터 Charter Communications ケーブル 통신 cable',
  'CSGP': '코스타 CoStar コスター 부동산 데이터 real estate',
  'SPY': '에스피와이 S&P500 미국지수 米国指数 美股 指数 índice indice ETF',
  'QQQ': '큐큐큐 나스닥100 ナスダック 纳斯达克 納斯達克 ETF',
  'VOO': '부 브이오오 S&P500 뱅가드 Vanguard ETF',
  'IVV': '아이브이브이 S&P500 아이셰어즈 iShares ETF',
  'VTI': '브이티아이 미국전체시장 total market ETF',
  'IWM': '러셀2000 소형주 Russell small cap ETF',
  'DIA': '다우존스 다이아 Dow Jones ダウ ETF',
  'SCHD': '슈드 배당 dividend 配当 股息 ETF',
  'VGT': '기술주 technology テクノロジー 科技 ETF',
  'XLK': '기술 섹터 technology 科技 ETF',
  'XLF': '금융 섹터 financial finance 金融 ETF',
  'XLE': '에너지 섹터 energy 能源 ETF',
  'XLV': '헬스케어 의료 health care 医療 ETF',
  'XLI': '산업재 industrial 工业 工業 ETF',
  'XLY': '임의소비재 consumer discretionary ETF',
  'XLP': '필수소비재 consumer staples ETF',
  'XLU': '유틸리티 전력 utility ETF',
  'XLB': '소재 materials 材料 ETF',
  'XLRE': '부동산 real estate リート 房地产 房地產 ETF',
  'SMH': '반도체 semiconductor 半導体 半导体 半導體 ETF',
  'SOXX': '반도체 semiconductor 半導体 半导体 半導體 ETF',
  'ARKK': '아크 혁신 innovation イノベーション 创新 創新 ETF',
  'TLT': '미국채 장기채 treasury bond 債券 债券 ETF',
  'HYG': '하이일드 채권 high yield bond ETF',
  'LQD': '회사채 투자등급 corporate bond ETF',
  'BND': '채권 bond 債券 债券 ETF',
  'AGG': '종합채권 aggregate bond ETF',
  'SHY': '단기채 short treasury bond ETF',
  'IEF': '중기채 treasury bond ETF',
  'GLD': '금 gold ゴールド 黄金 黃金 oro or ETF',
  'SLV': '은 silver シルバー 白银 白銀 plata argent ETF',
  'USO': '원유 오일 oil crude petróleo petrole ETF',
  'UNG': '천연가스 natural gas gas naturel ETF',
  'EEM': '신흥국 emerging markets 新兴市场 新興市場 ETF',
  'EFA': '선진국 developed markets ETF',
  'VXUS': '미국제외 해외주식 international ex us ETF',
  'VEA': '선진국 developed markets ETF',
  'VNQ': '부동산 리츠 REIT real estate ETF',
  'QQQM': '나스닥100 NASDAQ ETF',
  'SQQQ': '나스닥 인버스 inverse short ETF',
  'SOXL': '반도체 레버리지 leveraged semiconductor ETF',
  'TECL': '기술주 레버리지 leveraged technology ETF',
  'SPXL': 'S&P500 레버리지 leveraged ETF',
  'UPRO': 'S&P500 레버리지 leveraged ETF',
  'TNA': '러셀2000 레버리지 small cap leveraged ETF',
  'JEPI': '월배당 커버드콜 income dividend covered call ETF',
  'JEPQ': '나스닥 월배당 커버드콜 income covered call ETF',
  'QYLD': '나스닥 커버드콜 covered call dividend ETF',
  'IBIT': '비트코인 bitcoin ビットコイン 比特币 比特幣 ETF',
  'BITO': '비트코인 bitcoin futures 선물 ETF',
  'GC1!': '금 골드 gold ゴールド 黄金 黃金 oro or 귀금속 precious metal',
  'SI1!': '은 실버 silver シルバー 白银 白銀 plata argent 귀금속 precious metal',
  'HG1!': '구리 동 copper 銅 铜 c도브레 cobre 산업금속 metal',
  'PL1!': '백금 플래티넘 platinum プラチナ 铂金 鉑金 platino',
  'PA1!': '팔라듐 palladium パラジウム 钯 鈀',
  'CL1!': '원유 WTI crude oil 오일 석유 petróleo petrole energy',
  'BRN1!': '브렌트유 brent crude oil 원유 석유 petróleo petrole',
  'NG1!': '천연가스 natural gas ガス 天然气 天然氣 gas',
  'RB1!': '휘발유 가솔린 gasoline ガソリン 汽油',
  'HO1!': '난방유 heating oil diesel fuel',
  'ZC1!': '옥수수 corn トウモロコシ 玉米 maiz maïs',
  'ZW1!': '밀 wheat 小麦 小麥 trigo blé',
  'ZS1!': '대두 콩 soybean soybeans 大豆 soja',
  'ZL1!': '대두유 콩기름 soybean oil 豆油 aceite',
  'ZM1!': '대두박 soybean meal 豆粕',
  'ZO1!': '귀리 oats オート麦 燕麦 燕麥 avena avoine',
  'ZR1!': '쌀 rice rough rice 米 arroz riz',
  'KC1!': '커피 coffee コーヒー 咖啡 cafe café',
  'SB1!': '설탕 sugar 砂糖 白糖 azucar sucre',
  'CC1!': '코코아 cocoa cacao カカオ 可可',
  'CT1!': '면화 cotton 綿 棉花 algodon coton',
  'OJ1!': '오렌지주스 orange juice オレンジジュース 橙汁',
  'LBR1!': '목재 lumber timber 木材 madera bois',
  'LE1!': '생우 live cattle 소 牛 ganado bétail',
  'GF1!': '비육우 feeder cattle 소 牛 ganado',
  'HE1!': '돼지 lean hogs 豚 猪 豬 cerdo porc',
  'DC1!': '우유 milk dairy ミルク 牛奶 leche lait',
  'FEF1!': '철광석 iron ore 鉄鉱石 铁矿石 鐵礦石 mineral hierro',
  'ALI1!': '알루미늄 aluminum aluminium アルミ 铝 鋁',
  'ZNC1!': '아연 zinc 亜鉛 锌 鋅',
  'NIC1!': '니켈 nickel ニッケル 镍 鎳',
  'LED1!': '납 lead 鉛 铅',
  'TIN1!': '주석 tin 錫 锡 estaño étain',
  'QX1!': '석탄 coal 石炭 煤炭 carbon charbon',
  'UX1!': '우라늄 uranium ウラン 铀 鈾',
  'EH1!': '에탄올 ethanol biofuel 바이오연료',
  'RS1!': '카놀라 canola 菜籽油 rapeseed',
  'COM1!': '유채 rapeseed canola colza',
  'FCPO1!': '팜유 palm oil 棕榈油 棕櫚油',
  'RSS31!': '고무 rubber ゴム 橡胶 橡膠 caucho caoutchouc',
  'PN1!': '프로판 propane 가스 gas',
  'ULSD1!': '디젤 diesel 경유 fuel',
  'QS1!': '경유 가스오일 gasoil diesel',
  'ECF1!': '탄소배출권 carbon emissions carbone carbono 碳排放',
  'DX1!': '달러인덱스 dollar index 美元指数 美元指數',
  'BDI': '발틱운임 Baltic Dry Index 해운 운임 freight shipping',
  'FBX1!': '운임 freight shipping 물류 物流',
  'GOLD': '금 현물 gold spot 黄金 黃金',
  'SILVER': '은 현물 silver spot 白银 白銀',
  'COPPER': '구리 현물 copper spot 銅 铜',
  'TSM': 'TSMC 티에스엠씨 대만반도체 台積電 台积电 台湾半導体 반도체 semiconductor',
  '005930': '삼성전자 삼성 サムスン電子 三星电子 三星電子 Samsung Electronics 반도체',
  '2222': '사우디 아람코 Saudi Aramco サウジアラムコ 沙特阿美 석유 oil energy',
  '0700': '텐센트 Tencent テンセント 腾讯 騰訊 게임 중국 internet',
  '9988': '알리바바 Alibaba アリババ 阿里巴巴 전자상거래 ecommerce',
  'NOVO_B': '노보노디스크 Novo Nordisk ノボノルディスク 诺和诺德 諾和諾德 비만 diabetes',
  'MC': '루이비통 LVMH エルブイエムエイチ 路威酩轩 路威酩軒 luxury 명품',
  '7203': '토요타 도요타 Toyota トヨタ 丰田 豐田 자동차 car',
  'SAP': 'SAP 에스에이피 サップ software ソフト웨어 软件 軟體',
  'NESN': '네슬레 Nestle Nestlé ネスレ 雀巢 food 식품',
  'ROG': '로슈 Roche ロシュ 罗氏 羅氏 제약 pharma',
  'NOVN': '노바티스 Novartis ノバルティス 诺华 諾華 제약 pharma',
  'AZN': '아스트라제네카 AstraZeneca アストラゼネカ 阿斯利康 제약 pharma',
  'SHEL': '쉘 Shell シェル 壳牌 殼牌 석유 oil energy',
  'HSBA': 'HSBC 에이치에스비씨 汇丰 匯豐 은행 bank',
  'BHP': 'BHP 비에이치피 광산 mining iron ore 철광석',
  '300750': 'CATL 닝더스다이 宁德时代 寧德時代 배터리 battery',
  '6758': '소니 Sony ソニー 索尼 전자 entertainment',
  '8306': '미쓰비시UFJ MUFG 三菱UFJ 은행 bank',
  'RELIANCE': '릴라이언스 Reliance リライアンス 인도 india energy',
  '1398': '공상은행 ICBC 工商银行 工商銀行 중국은행 bank',
  '0941': '차이나모바일 China Mobile 中国移动 中國移動 통신 telecom',
  '3690': '메이투안 Meituan 美团 美團 배달 delivery',
  '1211': 'BYD 비야디 比亚迪 比亞迪 전기차 EV battery',
  'RMS': '에르메스 Hermes Hermès エルメス 爱马仕 愛馬仕 명품 luxury',
  'SIE': '지멘스 Siemens シーメンス 西门子 西門子 industrial',
  'TTE': '토탈에너지 TotalEnergies トタル 能源 energy oil',
  'CBA': '커먼웰스은행 Commonwealth Bank 호주은행 bank australia',
  'ULVR': '유니레버 Unilever ユニリーバ 联合利华 聯合利華 consumer',
  '1299': 'AIA 에이아이에이 友邦保险 友邦保險 보험 insurance',
  'BTC': '비트코인 bitcoin ビットコイン 比特币 比特幣 биткоин crypto',
  'ETH': '이더리움 ethereum イーサリアム 以太坊 эфир crypto',
  'USDT': '테더 tether 泰达币 泰達幣 스테이블코인 stablecoin',
  'XRP': '리플 ripple エックスアールピー 瑞波 crypto',
  'BNB': '비앤비 바이낸스코인 Binance coin 币安幣 币安币 crypto',
  'SOL': '솔라나 solana ソラナ 索拉纳 索拉納 crypto',
  'USDC': '유에스디코인 USD Coin 스테이블코인 stablecoin',
  'TRX': '트론 tron トロン 波场 波場 crypto',
  'DOGE': '도지코인 dogecoin ドージコイン 狗狗币 狗狗幣 crypto',
  'ADA': '카르다노 에이다 cardano ada カルダノ 艾达 艾達 crypto',
  'HYPE': '하이퍼리퀴드 hyperliquid hype crypto',
  'SUI': '수이 sui スイ crypto',
  'BCH': '비트코인캐시 bitcoin cash ビットコインキャッシュ crypto',
  'LINK': '체인링크 chainlink チェーンリンク crypto oracle',
  'XLM': '스텔라 stellar lumen ステラ 恒星币 恒星幣 crypto',
  'AVAX': '아발란체 avalanche アバランチ 雪崩 crypto',
  'LEO': '레오 leo unus sed leo crypto',
  'TON': '톤코인 toncoin トンコイン crypto',
  'LTC': '라이트코인 litecoin ライトコイン 莱特币 萊特幣 crypto',
  'SHIB': '시바이누 shiba inu 柴犬币 柴犬幣 crypto meme',
  'HBAR': '헤데라 hedera ヘデラ crypto',
  'DOT': '폴카닷 polkadot ポルカドット 波卡 crypto',
  'UNI': '유니스왑 uniswap ユニスワップ crypto defi',
  'XMR': '모네로 monero モネロ 门罗币 門羅幣 crypto',
  'DAI': '다이 dai ス테이블코인 stablecoin',
  'APT': '앱토스 aptos アプトス crypto',
  'PEPE': '페페 pepe ペペ crypto meme',
  'OKB': '오케이비 OKB crypto exchange token',
  'TAO': '비텐서 bittensor tao crypto ai',
  'ICP': '인터넷컴퓨터 internet computer crypto',
  'ETC': '이더리움클래식 ethereum classic crypto',
  'NEAR': '니어프로토콜 near protocol ニア crypto',
  'AAVE': '아베 에이브 aave defi crypto',
  'ONDO': '온도 ondo finance rwa crypto',
  'POL': '폴리곤 polygon matic crypto',
  'KAS': '카스파 kaspa crypto',
  'CRO': '크로노스 cronos crypto.com crypto',
  'ATOM': '코스모스 cosmos atom crypto',
  'ALGO': '알고랜드 algorand crypto',
  'VET': '비체인 vechain crypto',
  'FIL': '파일코인 filecoin crypto storage',
  'ARB': '아비트럼 arbitrum crypto layer2',
  'KCS': '쿠코인토큰 kucoin token crypto',
  'OP': '옵티미즘 optimism crypto layer2',
  'WLD': '월드코인 worldcoin crypto',
  'SEI': '세이 sei crypto',
  'BONK': '봉크 bonk crypto meme',
  'INJ': '인젝티브 injective crypto',
  'FET': '페치 fetch ai artificial superintelligence crypto',
  'RENDER': '렌더 render crypto ai gpu',
  'EWY': '한국 코리아 korea 韩国 韓國 ETF 국가 country',
  'EWJ': '일본 japan 日本 ETF 국가 country',
  'FXI': '중국 대형주 china 中国 中國 ETF country',
  'MCHI': '중국 china 中国 中國 ETF country',
  'EWT': '대만 타이완 taiwan 台湾 台灣 ETF country',
  'INDA': '인도 india 印度 ETF country',
  'VGK': '유럽 europe europa 欧洲 歐洲 ETF region',
  'EWG': '독일 germany deutschland ドイツ 德国 德國 ETF country',
  'EWQ': '프랑스 france フランス 法国 法國 ETF country',
  'EWZ': '브라질 brazil brasil ブラジル 巴西 ETF country',
  'EWW': '멕시코 mexico méxico メキシコ 墨西哥 ETF country',
  'VIX': '공포지수 변동성 volatility fear index 恐慌指数 恐慌指數',
  'UVXY': '변동성 레버리지 volatility VIX leveraged fear ETF',
  'SVXY': '변동성 인버스 inverse volatility VIX ETF',
  'MOVE': '채권 변동성 bond volatility treasury fear index',
  'VVIX': 'VIX 변동성 volatility of volatility fear index',
  'US10Y': '미국 10년물 금리 국채 treasury yield bond rate',
  'US02Y': '미국 2년물 금리 국채 treasury yield bond rate',
  'US30Y': '미국 30년물 금리 국채 treasury yield bond rate',
  'SMCI': '슈퍼마이크로 Super Micro Computer 서버 AI 인프라 infrastructure',
  'DELL': '델 Dell デル 서버 PC AI 인프라 infrastructure',
  'HPE': '휴렛팩커드 HPE Hewlett Packard Enterprise 서버 AI 인프라',
  'VRT': '버티브 Vertiv 전력 냉각 데이터센터 AI infrastructure',
  '000660': 'SK하이닉스 하이닉스 Hynix 半导体 半導體 메모리 반도체',
  '005380': '현대차 현대자동차 Hyundai Motor ヒョンデ 现代 現代 자동차',
  '035420': '네이버 NAVER ネイバー 검색 포털 인터넷',
  '035720': '카카오 Kakao カカオ 메신저 플랫폼 인터넷',
  '051910': 'LG화학 엘지화학 LG Chem 배터리 화학',
  '373220': 'LG에너지솔루션 엘지에너지솔루션 LG Energy Solution 배터리 battery',
  '9984': '소프트뱅크 SoftBank ソフトバンク 일본 투자 통신',
  '8035': '도쿄일렉트론 Tokyo Electron 반도체 장비 semiconductor equipment',
  '6861': '키엔스 Keyence キーエンス 자동화 센서 automation',
  '4063': '신에츠화학 Shin-Etsu Chemical 반도체 소재 chemical',
  '6098': '리크루트 Recruit リクルート HR 채용 일본',
  'NOC': '노스롭그루먼 Northrop Grumman 방산 defense aerospace',
  'GD': '제너럴다이내믹스 General Dynamics 방산 defense aerospace',
  'LHX': 'L3해리스 L3Harris 방산 defense aerospace',
  'ETR': '엔터지 Entergy 전력 원전 utility nuclear',
  'VST': '비스트라 Vistra 전력 발전 utility power',
  'PWR': '콴타서비스 Quanta Services 전력 인프라 grid infrastructure',
  'IONQ':
      '아이온큐 이온큐 IonQ quantum computing 퀀텀컴퓨팅 양자컴퓨터 양자컴퓨팅 量子计算 量子運算 computación cuántica computacao quantica computação quântica informatique quantique Quantencomputing квантовые вычисления',
  'RGTI':
      '리게티 Rigetti quantum computing 퀀텀컴퓨팅 양자컴퓨터 양자컴퓨팅 量子计算 量子運算 computación cuántica computacao quantica computação quântica informatique quantique Quantencomputing квантовые вычисления',
  'QUBT':
      '퀀텀컴퓨팅 Quantum Computing Inc quantum computing 퀀텀컴퓨팅 양자컴퓨터 양자컴퓨팅 量子计算 量子運算 computación cuántica computacao quantica computação quântica informatique quantique Quantencomputing квантовые вычисления',
  'QBTS':
      '디웨이브 D-Wave quantum computing 퀀텀컴퓨팅 양자컴퓨터 양자컴퓨팅 量子计算 量子運算 computación cuántica computacao quantica computação quântica informatique quantique Quantencomputing квантовые вычисления',
  'QTUM':
      '퀀텀 ETF Defiance Quantum ETF quantum computing 퀀텀컴퓨팅 양자컴퓨터 양자컴퓨팅 量子计算 量子運算 computación cuántica computacao quantica computação quântica informatique quantique Quantencomputing квантовые вычисления',
};

const Map<String, String> _commoditySearchAliases = {
  'commoditygold':
      '금 골드 gold ouro oro or золото Gold ゴールド 黄金 黃金 precious metal 귀금속',
  'commoditysilver':
      '은 실버 silver prata plata argent серебро Silber シルバー 白银 白銀 precious metal 귀금속',
  'commoditycopper':
      '구리 동 copper cobre cuivre медь Kupfer 銅 铜 산업금속 industrial metal',
  'commodityplatinum':
      '백금 플래티넘 platinum platina platino platine платина Platin プラチナ 铂金 鉑金',
  'commoditypalladium':
      '팔라듐 palladium paladio palladium палладий Palladium パラジウム 钯 鈀',
  'commoditywtiCrude':
      '원유 석유 오일 WTI crude oil petroleo petróleo petrole pétrole нефть Öl 原油 石油',
  'commoditybrentCrude':
      '브렌트유 원유 석유 brent crude oil petroleo petróleo petrole pétrole нефть Öl 原油 石油',
  'commoditynaturalGas':
      '천연가스 가스 natural gas gas gaz природный газ Erdgas 天然气 天然氣',
  'commoditygasoline':
      '휘발유 가솔린 gasoline gasolina essence бензин Benzin ガソリン 汽油',
  'commodityheatingOil':
      '난방유 heating oil fuel oil gasoleo gasóleo fioul мазут Heizöl',
  'commoditycorn': '옥수수 corn milho maiz maíz mais maïs кукуруза Mais トウモロコシ 玉米',
  'commoditywheat': '밀 소맥 wheat trigo ble blé пшеница Weizen 小麦 小麥',
  'commoditysoybeans': '대두 콩 soybean soybeans soja соя Sojabohnen 大豆',
  'commoditysoybeanOil':
      '대두유 콩기름 soybean oil oleo de soja aceite de soja huile de soja соевое масло 豆油',
  'commoditysoybeanMeal':
      '대두박 soybean meal farelo de soja harina de soja tourteau de soja соевый шрот 豆粕',
  'commodityoats': '귀리 oats aveia avena avoine овес овёс Hafer オート麦 燕麦 燕麥',
  'commodityroughRice': '쌀 현미 rice rough rice arroz riz рис Reis 米',
  'commoditycoffee': '커피 coffee cafe café кофе Kaffee コーヒー 咖啡',
  'commoditysugar':
      '설탕 sugar acucar açúcar azucar azúcar sucre сахар Zucker 砂糖 白糖',
  'commoditycocoa': '코코아 cocoa cacao какао Kakao カカオ 可可',
  'commoditycotton':
      '면화 cotton algodao algodão algodon algodón coton хлопок Baumwolle 綿 棉花',
  'commodityorangeJuice':
      '오렌지주스 orange juice suco de laranja zumo de naranja jus orange апельсиновый сок Orangensaft 橙汁',
  'commoditylumber': '목재 lumber timber madeira madera bois древесина Holz 木材',
  'commodityliveCattle':
      '생우 소 live cattle gado ganado betail bétail крупный рогатый скот Rinder 牛',
  'commodityfeederCattle':
      '비육우 소 feeder cattle gado ganado betail bétail Rinder 牛',
  'commodityleanHogs': '돼지 lean hogs porco cerdo porc свиньи Schwein 豚 猪 豬',
  'commoditymilk': '우유 milk leite leche lait молоко Milch ミルク 牛奶',
  'commodityironOre':
      '철광석 iron ore minerio de ferro minério de ferro mineral de hierro minerai de fer железная руда Eisenerz 鉄鉱石 铁矿石 鐵礦石',
  'commodityaluminum':
      '알루미늄 aluminum aluminium aluminio aluminium алюминий Aluminium アルミ 铝 鋁',
  'commodityzinc': '아연 zinc zinco zinc цинк Zink 亜鉛 锌 鋅',
  'commoditynickel': '니켈 nickel niquel níquel nickel никель Nickel ニッケル 镍 鎳',
  'commoditylead': '납 lead chumbo plomo plomb свинец Blei 鉛 铅',
  'commoditytin': '주석 tin estanho estano estaño etain étain олово Zinn 錫 锡',
  'commoditycoal':
      '석탄 coal carvao carvão carbon carbón charbon уголь Kohle 石炭 煤炭',
  'commodityuranium': '우라늄 uranium uranio uranium уран Uran ウラン 铀 鈾',
  'commodityethanol':
      '에탄올 ethanol etanol etanol ethanol этанол Ethanol 바이오연료 biofuel',
  'commoditycanola': '카놀라 canola colza рапс Raps 菜籽油',
  'commodityrapeseed': '유채 rapeseed canola colza рапс Raps 菜籽',
  'commoditypalmOil':
      '팜유 palm oil oleo de palma aceite de palma huile de palme пальмовое масло Palmöl 棕榈油 棕櫚油',
  'commodityrubber':
      '고무 rubber borracha caucho caoutchouc резина Gummi ゴム 橡胶 橡膠',
  'commoditypropane': '프로판 propane propano propane пропан Propan 가스 gas',
  'commoditydiesel': '디젤 경유 diesel diesel diesel дизель Diesel',
  'commoditygasoil':
      '가스오일 경유 gasoil gasoleo gasóleo gasoil газойль Gasöl diesel',
  'commoditycarbon':
      '탄소배출권 carbon emissions carbono carbone углерод CO2 Kohlenstoff 碳排放',
  'commodityusDollarIndex':
      '달러인덱스 달러 지수 US Dollar Index indice dolar índice dólar indice dollar долларовый индекс Dollarindex 美元指数 美元指數',
  'commoditybalticDry':
      '발틱운임 Baltic Dry Index 해운 운임 freight shipping frete flete fret фрахт Frachtrate',
  'commodityfreight': '운임 freight shipping frete flete fret фрахт Fracht 물류 物流',
  'commoditygoldSpot': '금 현물 gold spot ouro oro or золото Gold ゴールド 黄金 黃金',
  'commoditysilverSpot':
      '은 현물 silver spot prata plata argent серебро Silber シルバー 白银 白銀',
  'commoditycopperSpot': '구리 현물 copper spot cobre cuivre медь Kupfer 銅 铜',
};

const Map<String, String> _extraChartSearchAliases = {
  'AAPL': '애플 아이폰 iphone mac 맥 苹果 蘋果 アップル',
  'MSFT': '마이크로소프트 윈도우 오피스 클라우드 Microsoft 微软 微軟 マイクロソフト',
  'NVDA': '엔비디아 엔디비아 nvidia 그래픽카드 GPU AI 반도체 英伟达 輝達 エヌビディア',
  'AMZN': '아마존 amazon 이커머스 클라우드 AWS 亚马逊 亞馬遜 アマゾン',
  'GOOGL': '구글 알파벳 google alphabet 검색 유튜브 youtube 谷歌 グーグル',
  'GOOG': '구글 알파벳 google alphabet 검색 유튜브 youtube 谷歌 グーグル',
  'META': '메타 페이스북 인스타그램 instagram facebook 메타버스 Meta 脸书 臉書',
  'TSLA': '테슬라 전기차 EV 일론머스크 Tesla 特斯拉 テスラ',
  'AVGO': '브로드컴 broadcom 반도체 AI 네트워크 博通 ブロードコム',
  'BRK.B': '버크셔 해서웨이 워렌버핏 berkshire hathaway 巴菲特 バークシャー',
  'LLY': '일라이릴리 릴리 비만 당뇨 제약 Eli Lilly 礼来 禮來 イーライリリー',
  'JPM': '제이피모건 JP모건 은행 금융 JPMorgan 摩根大通 JPモルガン',
  'V': '비자 visa 카드 결제 支付 ビザ',
  'MA': '마스터카드 mastercard 카드 결제 支付 マスターカード',
  'UNH': '유나이티드헬스 유나이티드헬스케어 건강보험 헬스케어 UnitedHealth',
  'XOM': '엑슨모빌 엑손모빌 석유 에너지 Exxon Mobil oil energy 埃克森美孚',
  'COST': '코스트코 costco 리테일 할인마트 コストコ',
  'HD': '홈디포 home depot 주택 건축 인테리어 家得宝 ホームデポ',
  'NFLX': '넷플릭스 netflix 스트리밍 OTT ネットフリックス 奈飞 奈飛',
  'PG': '피앤지 P&G 프록터앤갬블 생활용품 Procter Gamble 宝洁 寶潔',
  'JNJ': '존슨앤존슨 JNJ 제약 헬스케어 Johnson & Johnson 強生',
  'WMT': '월마트 walmart 리테일 할인마트 沃尔玛 ウォルマート',
  'ABBV': '애브비 AbbVie 제약 바이오 botox 보톡스 艾伯维',
  'BAC': '뱅크오브아메리카 BOA 은행 Bank of America 美国银行',
  'CRM': '세일즈포스 salesforce CRM 클라우드 소프트웨어',
  'ORCL': '오라클 oracle 데이터베이스 클라우드 甲骨文 オラクル',
  'KO': '코카콜라 coca cola 음료 可口可乐 コカコーラ',
  'CVX': '셰브론 쉐브론 chevron 석유 에너지 oil energy 雪佛龙',
  'AMD': '에이엠디 AMD 라이젠 반도체 CPU GPU 超微 半导体',
  'MRK': '머크 merck 제약 키트루다 默沙东 メルク',
  'CSCO': '시스코 cisco 네트워크 통신 보안 思科 シスコ',
  'WFC': '웰스파고 wells fargo 은행 금융 富国银行',
  'MCD': '맥도날드 mcdonalds 햄버거 패스트푸드 麦当劳 マクドナルド',
  'PEP': '펩시 펩시코 pepsi pepsico 음료 스낵 百事 ペプシ',
  'LIN': '린데 linde 산업가스 수소 chemical gas',
  'ADBE': '어도비 adobe 포토샵 creative cloud 소프트웨어 アドビ',
  'TMO': '써모피셔 thermo fisher 생명과학 바이오 장비',
  'GE': 'GE 지이 제너럴일렉트릭 항공 에너지 aerospace',
  'IBM': '아이비엠 IBM AI 왓슨 서버 클라우드',
  'QCOM': '퀄컴 qualcomm 스냅드래곤 반도체 통신 高通',
  'CAT': '캐터필러 caterpillar 중장비 건설 광산 卡特彼勒',
  'INTU': '인튜이트 intuit 터보택스 퀵북스 핀테크 세금',
  'DIS': '디즈니 disney OTT 디즈니플러스 테마파크 迪士尼',
  'TXN': '텍사스인스트루먼트 TI 반도체 Texas Instruments 德州仪器',
  'AMAT': '어플라이드머티리얼즈 applied materials 반도체 장비 应用材料',
  'GS': '골드만삭스 Goldman Sachs 투자은행 금융 高盛',
  'NOW': '서비스나우 ServiceNow 클라우드 워크플로우 소프트웨어',
  'ISRG': '인튜이티브서지컬 다빈치로봇 수술로봇 의료기기',
  'VZ': '버라이즌 verizon 통신 5G',
  'RTX': 'RTX 레이시온 방산 항공 미사일 defense',
  'BKNG': '부킹홀딩스 booking 부킹닷컴 여행 호텔',
  'SPGI': 'S&P글로벌 S&P Global 신용평가 지수 데이터',
  'LOW': '로우스 lowes 주택 인테리어 건축 리테일',
  'PFE': '화이자 pfizer 제약 백신 辉瑞 ファイザー',
  'HON': '하니웰 honeywell 자동화 항공 산업',
  'NKE': '나이키 nike 스포츠 신발 의류 耐克 ナイキ',
  'UBER': '우버 uber 차량공유 배달 모빌리티',
  'CMCSA': '컴캐스트 comcast 케이블 미디어 통신',
  'AMGN': '암젠 amgen 바이오 제약',
  'BA': '보잉 boeing 항공기 방산 波音 ボーイング',
  'UNP': '유니온퍼시픽 union pacific 철도 railroad',
  'SBUX': '스타벅스 starbucks 커피 スターバックス 星巴克',
  'PANW': '팔로알토네트웍스 palo alto cybersecurity 보안',
  'PLTR': '팔란티어 palantir AI 데이터 방산',
  'MU': '마이크론 micron 메모리 반도체 DRAM NAND 美光',
  'LRCX': '램리서치 lam research 반도체 장비',
  'ADP': 'ADP 급여 인사 HR payroll',
  'DE': '디어 존디어 deere 농기계 트랙터',
  'GILD': '길리어드 gilead 바이오 제약',
  'COP': '코노코필립스 conoco phillips 석유 에너지',
  'TJX': '티제이엑스 TJX 리테일 할인매장',
  'ADI': '아날로그디바이시스 analog devices 반도체',
  'C': '씨티그룹 citi citigroup 은행 금융',
  'APP': '앱러빈 applovin 광고 게임 AI',
  'SCHW': '찰스슈왑 schwab 증권 브로커리지',
  'ANET': '아리스타네트웍스 arista 네트워크 데이터센터',
  'MDLZ': '몬델리즈 mondelez 오레오 과자 스낵',
  'SYK': '스트라이커 stryker 의료기기 헬스케어',
  'BLK': '블랙록 blackrock 자산운용 ETF',
  'ETN': '이튼 eaton 전력 전기 인프라',
  'MMC': '마시맥레넌 marsh mclennan 보험 컨설팅',
  'REGN': '리제네론 regeneron 바이오 제약',
  'VRTX': '버텍스 vertex pharma 제약 바이오',
  'LMT': '록히드마틴 lockheed martin 방산 항공 defense',
  'ELV': '엘레번스헬스 elevance health 보험 헬스케어',
  'UPS': '유피에스 UPS 물류 택배 배송',
  'PGR': '프로그레시브 progressive 보험',
  'AMT': '아메리칸타워 american tower 통신탑 리츠',
  'NEE': '넥스트에라에너지 nextera energy 전력 신재생',
  'SO': '서던컴퍼니 southern company 전력 유틸리티',
  'KLAC': 'KLA 케이엘에이 반도체 장비 검사',
  'BX': '블랙스톤 blackstone 사모펀드 부동산',
  'KKR': 'KKR 사모펀드 투자자산운용',
  'SHOP': '쇼피파이 shopify 이커머스 쇼핑몰',
  'MELI': '메르카도리브레 mercadolibre 남미 이커머스',
  'ABNB': '에어비앤비 airbnb 여행 숙박',
  'RIVN': '리비안 rivian 전기차 EV',
  'SNOW': '스노우플레이크 snowflake 데이터 클라우드',
  'COIN': '코인베이스 coinbase 암호화폐 거래소 코인',
  'MSTR': '마이크로스트래티지 microstrategy 비트코인 bitcoin',
  'HOOD': '로빈후드 robinhood 증권 핀테크',
  'ASML': 'ASML 에이에스엠엘 반도체 장비 노광 네덜란드',
  'INTC': '인텔 intel 반도체 CPU',
  'ARM': '암 arm 반도체 설계',
  'TMUS': '티모바일 t-mobile 통신 5G',
  'STX': '씨게이트 seagate 하드디스크 저장장치',
  'MRVL': '마벨 marvell 반도체 네트워크',
  'WDC': '웨스턴디지털 western digital 저장장치 HDD SSD',
  'CRWD': '크라우드스트라이크 crowdstrike 보안 사이버보안',
  'PDD': '핀둬둬 테무 PDD temu 중국 이커머스',
  'CEG': '컨스텔레이션에너지 constellation energy 원전 전력',
  'CDNS': '케이던스 cadence 반도체 설계 EDA',
  'SNPS': '시놉시스 synopsys 반도체 설계 EDA',
  'MAR': '메리어트 marriott 호텔 여행',
  'FTNT': '포티넷 fortinet 보안 사이버보안',
  'CSX': 'CSX 철도 물류 railroad',
  'MNST': '몬스터베버리지 monster beverage 에너지드링크',
  'NXPI': 'NXP 반도체 자동차반도체',
  'MPWR': '모놀리식파워 monolithic power 전력반도체',
  'DDOG': '데이터독 datadog 클라우드 모니터링',
  'ROST': '로스스토어 ross stores 할인 리테일',
  'ORLY': '오라일리 오토파츠 OReilly 자동차부품',
  'AEP': '아메리칸일렉트릭파워 전력 유틸리티',
  'CTAS': '신타스 cintas 유니폼 서비스',
  'WBD': '워너브라더스디스커버리 HBO 미디어',
  'DASH': '도어대시 doordash 배달 음식',
  'BKR': '베이커휴즈 baker hughes 에너지 장비',
  'PCAR': '파카 paccar 트럭',
  'FANG': '다이아몬드백에너지 diamondback oil energy',
  'EA': '일렉트로닉아츠 EA 게임',
  'EXC': '엑셀론 exelon 전력 유틸리티',
  'KDP': '큐리그닥터페퍼 keurig dr pepper 음료',
  'PAYX': '페이첵스 paychex 급여 HR',
  'XEL': '엑셀에너지 xcel energy 전력',
  'FAST': '패스널 fastenal 산업용품',
  'TEAM': '아틀라시안 atlassian jira 소프트웨어',
  'IDXX': '아이덱스 idexx 반려동물 진단',
  'BIIB': '바이오젠 biogen 바이오 제약',
  'CSGP': '코스타그룹 costar 부동산 데이터',
  'ZS': '지스케일러 zscaler 보안',
  'TTD': '트레이드데스크 trade desk 광고',
  'WDAY': '워크데이 workday HR 클라우드',
  'VRSK': '베리스크 verisk 보험 데이터',
  'MCHP': '마이크로칩 microchip 반도체',
  'GFS': '글로벌파운드리스 globalfoundries 반도체 파운드리',
  'ON': '온세미 onsemi 반도체 전력',
  'MRNA': '모더나 moderna 백신 바이오',
  'MDB': '몽고디비 mongodb 데이터베이스',
  'NET': '클라우드플레어 cloudflare 보안 CDN',
  'RDDT': '레딧 reddit 커뮤니티 SNS',
  'HIMS': '힘스 hims 헬스케어 원격진료',
  'CELH': '셀시어스 celsius 에너지드링크',
  'DUOL': '듀오링고 duolingo 교육 언어 AI',
  'CAVA': '카바 cava 레스토랑',
  'SHAK': '쉐이크쉑 shake shack 레스토랑',
  'ELF': '엘프뷰티 elf beauty 화장품',
  'CART': '인스타카트 instacart 배달 장보기',
  'TOST': '토스트 toast 레스토랑 결제',
  'U': '유니티 unity 게임엔진',
  'PATH': '유아이패스 uipath 자동화 RPA',
  'AI': '씨쓰리에이아이 C3 AI 인공지능',
  'SOUN': '사운드하운드 soundhound AI 음성',
  'BBAI': '빅베어 BigBear AI 인공지능',
  'SERV': '서브로보틱스 serve robotics 로봇',
  'SYM': '심보틱 symbotic 로봇 자동화',
  'TER': '테라다인 teradyne 반도체 테스트 로봇',
  'IRBT': '아이로봇 irobot 로봇청소기',
  'OKLO': '오클로 oklo 원전 소형원전 SMR',
  'SMR': '뉴스케일 nuscale 소형원전 SMR',
  'LEU': '센트러스 centrus 우라늄 원전',
  'CCJ': '카메코 cameco 우라늄',
  'UEC': '우라늄에너지 uranium energy',
  'RKLB': '로켓랩 rocket lab 우주 로켓',
  'ASTS': 'AST스페이스모바일 우주통신 위성',
  'LUNR': '인튜이티브머신스 intuitive machines 달탐사 우주',
  'ACHR': '아처항공 archer aviation 전기항공 eVTOL',
  'JOBY': '조비항공 joby aviation 전기항공 eVTOL',
  'EVTL': '버티컬에어로스페이스 vertical aerospace eVTOL',
  'BLDE': '블레이드 blade air mobility 항공모빌리티',
  'LCID': '루시드 lucid 전기차 EV',
  'NIO': '니오 NIO 중국 전기차',
  'LI': '리오토 li auto 중국 전기차',
  'XPEV': '샤오펑 xpeng 중국 전기차',
  'BABA': '알리바바 alibaba 중국 이커머스',
  'BIDU': '바이두 baidu 중국 검색 AI',
  'JD': '징동닷컴 JD 중국 이커머스',
  'TME': '텐센트뮤직 tencent music 중국 음악',
  'BILI': '빌리빌리 bilibili 중국 영상',
  'BEKE': '베이커 KE holdings 중국 부동산',
  'YMM': '만방 full truck alliance 중국 물류',
  'SE': '씨리미티드 sea limited 동남아 쇼피 게임',
  'GRAB': '그랩 grab 동남아 슈퍼앱',
  'NU': '누뱅크 nubank 브라질 핀테크',
  'STNE': '스톤코 stoneco 브라질 핀테크',
  'PAGS': '팍세구로 pagseguro 브라질 핀테크',
  'CRSP': '크리스퍼 CRISPR 유전자편집 바이오',
  'EDIT': '에디타스 editas 유전자편집',
  'BEAM': '빔테라퓨틱스 beam 유전자편집',
  'NTLA': '인텔리아 intellia 유전자편집',
  'DNA': '깅코바이오웍스 ginkgo biotech',
  'RXRX': '리커전 recursion AI 바이오',
  'TEM': '템퍼스 tempus AI 헬스케어',
  'ENVX': '에노빅스 enovix 배터리',
  'QS': '퀀텀스케이프 quantumscape 전고체 배터리',
  'ALB': '앨버말 albemarle 리튬',
  'LAC': '리튬아메리카스 lithium americas 리튬',
  'PLL': '피드몬트리튬 piedmont lithium 리튬',
};

ExchangeListItem exchangeCurrencyItem(
  String id,
  String code,
  Color color,
) {
  return ExchangeListItem(
    id: id,
    symbolPath: 'FX_IDC-USD$code',
    color: color,
    icon: Icons.currency_exchange_rounded,
  );
}
